### ISSUE TITLE
Erigon2 prototype does not work on Goerli

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon-lib#257]
This is because Goerli has many blocks in the beginning that do not change state, and have the same state root hash as the genesis block. This is because Goerli uses Clique consensus, which does not have any mining rewards, so in the absence of transactions, nothing changes in the state.

this is the function that calculates the state root in the prototype:
https://github.com/ledgerwatch/erigon-lib/blob/3dea173d4289d497f6103ffc0ef6ae6548e65fb4/aggregator/aggregator.go#L1520

it constructs the update slices and calls ProcessUpdates
you need to figure out what happens if there are no updates, like in the case of initial Goerli block.

you can try to reproduce it with a test similar to these: https://github.com/ledgerwatch/erigon-lib/blob/main/commitment/hex_patricia_hashed_test.go

I usually run it with `go test ./commitment -v` to see the output
you can add another section that calls `ProduceUpdates` with no updates, to see what happens there

**Comment by AlexeyAkhunov** [comment]
Ethash (not clique is hard-coded): https://github.com/ledgerwatch/erigon/blob/devel/cmd/state/commands/erigon2.go#L241
you can derive consensus engine from chainConfig, which in turn can be read from the DB by code like this (you may need to copy it to the cmd/state): https://github.com/ledgerwatch/erigon/blob/d0123f52fd699f5c2af2115331d15f92d4fe086a/cmd/rpcdaemon/commands/eth_api.go#L128
example of derivation is here: https://github.com/ledgerwatch/erigon/blob/d0123f52fd699f5c2af2115331d15f92d4fe086a/eth/backend.go#L224

**Comment by awskii** [comment]
Tried to reproduce both in test on `HexPatriciaHashed` and on actual Goerli blocks.

Test 1 description:
 1. declare 2 accounts with balances.
 2. build and process update, store root hash
 3. `(*HexPatriciaHashed).Reset()`
 4. create empty updates, build and process, store root hash
 
Results in two different root hashes since step 3 resets tree state which affects further root hash calculation.

Test 2 description:
 1. declare 2 accounts with balances.
 2. build and process update, store root hash
 3. `(*HexPatriciaHashed).Reset()`
 4. copy updates from 1 step, build and process update, store root hash

Results with two equal hashes (as expected)

But I discovered from testing issue on real Goerli blocks that actually there ARE some updates after genesis block (first block hash evaluated as expected).
Those updates looks strange so I think my next step to look closer to `func (w *Writer) captureCommitmentData(trace bool)` and `func (w *Writer) captureCommitmentType(fType FileType, trace bool, f func(commTree *btree.BTree, h hash.Hash, key, val []byte))` - places where commitment BTree is updated. Maybe we incorrectly processing blocks or something like that. 

Why does they looks strange:
 - with increasing `blockNum` I see only one account commitment with flags `BALANCE_UPDATE|NONCE_UPDATE` and first 8 bits of balance increasing. 

E.g. for `blockNum = 4` balance is [8000000000000000001, 0, 0, 0]uint64, 
     for `blockNum = 2` balance is [2000000000000000001, 0, 0, 0]uint64
